# -*- coding: utf-8 -*-
"""IC_4_Concatenate_values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Fe5euYG2t0aLrTRzjpDKaBvGoGzL1qr
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Deep_learning/Deep\ Learning

"""#Absolute"""

import os
import pandas as pd
import numpy as np
from pathlib import Path
import pdb

# FS AND FO NAME CONVERSION
if __name__ == '__main__':

    markers = ["2markers", "3markers"]
    sec_markers = ["HLXHEE", "TOEHEE"]
    thr_markers = ["HLXPMT5HEE", "TOEPMT5HEE","HLXTOEHEE"]
    names = ["MidFoot", "ForeFoot", "Heel"]

    for marker in markers:
        if (marker == "2markers"):
            marker_name = sec_markers
        elif (marker == "3markers"):
            marker_name = thr_markers
        for name_marker in marker_name:
            for name in names:

                model_dir = f"Results/LSTM/TO/{marker}/{name_marker}/v1/models"
                fdir = f"{model_dir}/evaluation/{name}"
                sdir = f"{model_dir}/evaluation/"

                ignored = {".DS_Store", f"Icon\r"}
                folders = [x for x in os.listdir(fdir) if x not in ignored]

                mean_dist = dict()
                mean_width = dict()
                newFinal_fpr_tpr = pd.DataFrame()
                newFinal_error   = pd.DataFrame()

                for i in range(len(folders)):
                    dir_list = os.path.join(fdir, folders[i])
                    files = tuple(Path(f"{dir_list}/csv").glob("**/*.csv"))
                    
                    for j in range(len(files)):
                        filename = os.path.basename((files[j]))
                        if (filename[2:5] == "fpr"):
                              df = pd.read_csv(open(files[j], "r", ))
                              update_df_fpr_tpr = df.drop(['Unnamed: 0'], axis=1)
                        elif (filename[2:7] == "error"):
                              df = pd.read_csv(open(files[j], "r", ))
                              update_df = df.drop(['Unnamed: 0'], axis=1)
                              update_df_dist = update_df[:-1]
                           
                    new_fpr_tpr = pd.DataFrame({'FPR': pd.Series(update_df_fpr_tpr["FPR"], dtype="float64"),
                         'TPR':pd.Series(update_df_fpr_tpr["TPR"], dtype="float64"),
                         'Filename': pd.Series(update_df_fpr_tpr["FileName"], dtype="float64")})
                      
                    new_error = pd.DataFrame(
                        {'Distance_Error': pd.Series(update_df_dist["Error in distance"], dtype="float64"),
                        'Filename_dist': pd.Series(update_df_dist["FileName"], dtype="float64")})

                    if newFinal_fpr_tpr.empty:
                        newFinal_fpr_tpr = new_fpr_tpr
                        newFinal_error   = new_error
                    else:
                        newFinal_fpr_tpr = newFinal_fpr_tpr.append(new_fpr_tpr)
                        newFinal_error   = newFinal_error.append(new_error)
                # pdb.set_trace()
                newFinal_fpr_tpr.to_csv(os.path.join(f"{sdir}{name}-FPR_TPR_Total_Value.csv"))
                newFinal_error.to_csv(os.path.join(f"{sdir}{name}-error_Total_Value.csv"))

